# Generated by Django 3.2.7 on 2021-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210915_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
