# Generated by Django 3.2.7 on 2022-03-23 14:55

import django.core.validators
from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20211101_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='room_photos', validators=[rooms.models.file_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='How many people will be staying?', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
