FROM ubuntu:22.04

ARG PROJECT_NAME=airbnb-clone


ARG PYTHON_VERSION=3.9.4
ARG NODE_VERSION=16.20.0

## 환경 변수 설정
ENV HOME /root
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/bin:$PATH


RUN apt-get update && apt-get install -y \
    wget curl git vim nano nginx \
    openssh-server \
    make build-essential libssl-dev zlib1g-dev \
    libffi-dev libbz2-dev libreadline-dev llvm libncurses5-dev \ 
    libncursesw5-dev xz-utils liblzma-dev postgresql-server-dev-all libc-dev libc6-dev \
    supervisor
    #  tk-dev  \
    
# Create a directory for SSH daemon to run
RUN mkdir /var/run/sshd

# optional 둘중하나 선택 또는 모두
# root 암호 설정 
RUN echo "root:${PW}" | chpasswd

# python 설치 및 설정
## pyenv 설치
RUN curl https://pyenv.run | bash

## pyenv 초기화 설정
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bashrc \
    && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.bashrc \
    && echo 'eval "$(pyenv init --path)"' >> $HOME/.bashrc \
    && echo 'eval "$(pyenv init -)"' >> $HOME/.bashrc \
    && echo 'eval "$(pyenv virtualenv-init -)"' >> $HOME/.bashrc

## pyenv를 사용하여 Python 설치 (예: Python 3.7.9)
RUN bash -c "source $HOME/.bashrc && pyenv install ${PYTHON_VERSION}"

## pyenv 글로벌 Python 버전 설정
RUN bash -c "pyenv global ${PYTHON_VERSION}"


# project settings
WORKDIR /app/${PROJECT_NAME}
COPY . .

# node 셋팅
## node 설치
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
RUN /bin/bash -c "source $HOME/.nvm/nvm.sh \
    && nvm install ${NODE_VERSION} \
    && nvm use ${NODE_VERSION} \
    && npm install"



# # 프로젝트 폴더 생성 및 권한 설정
# RUN chown -R ${USERNAME}:${USERNAME} /app

# venv 설정
## Docker 이미지 빌드 과정에서 사용하는 쉘은 이미지 빌드를 위한 임시 쉘이라서 
## .bashrc 파일은 로드되지 않아서 pyenv로 설치한 python 으로 정상적으로 추가되지 않아서
## pyenv 로 설정한 python -m venv 안먹힘.
RUN /root/.pyenv/shims/python -m venv /app/myvenv
RUN echo "cd /app" >> $HOME/.bashrc \
    && echo 'source myvenv/bin/activate' >> $HOME/.bashrc \
    && echo 'cd ${PROJECT_NAME}' >> $HOME/.bashrc 


RUN /app/myvenv/bin/pip install --upgrade pip 
RUN /app/myvenv/bin/pip install -r requirements.txt


CMD ["python", "manage.py", "8080"]