# Generated by Django 3.2.7 on 2021-11-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20211101_2151'),
        ('lists', '0004_alter_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='rooms',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lists.list')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rooms.room')),
            ],
        ),
    ]
