# Generated by Django 3.2.7 on 2021-11-04 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20211104_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lists',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rooms',
            new_name='room',
        ),
    ]
